// Mocks generated by Mockito 5.0.16 from annotations
// in nyt_flutter/test/unit-tests/articles_list/data/remote/article_service_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nyt_flutter/articles_list/data/model/most_popular_response.dart'
    as _i2;

import 'article_service_impl_test.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMostPopularResponse_0 extends _i1.Fake
    implements _i2.MostPopularResponse {}

/// A class which mocks [MockArticleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockArticleService extends _i1.Mock
    implements _i3.MockArticleService {
  MockMockArticleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
  @override
  _i4.Future<_i2.MostPopularResponse> getTasks(String? apiKey) =>
      (super.noSuchMethod(Invocation.method(#getTasks, [apiKey]),
              returnValue: Future<_i2.MostPopularResponse>.value(
                  _FakeMostPopularResponse_0()))
          as _i4.Future<_i2.MostPopularResponse>);
}
